extends:
  - '@form8ion'
  - '@form8ion/cucumber'

parserOptions:
  ecmaVersion: 2022

overrides:
  - files: example.js
    rules:
      import/no-extraneous-dependencies: off

rules:
  import/extensions:
    - error
    - ignorePackages
